[package]
name = "cvgb"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
compact_str = "0.9.0"
enum-assoc = "1.2.4"
macroquad = "0.4.14"
modular-bitfield = "0.12.0"
thiserror = "2.0.12"
