[workspace]
members = [ "core" ]

[package]
name = "cvgb"
version = "0.1.0"
edition = "2024"

[dependencies]

cvgb-core = { path = "core" }

arrayvec = "0.7.6"
bytemuck = "1.23.2"
compact_str = "0.9.0"
cpal = { version = "0.16.0", features = ["jack"] }
egui = "0.33.0"
egui-wgpu = "0.33.0"
egui-winit = "0.33.0"
enum-assoc = "1.2.4"
enum_dispatch = "0.3.13"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.27"
modular-bitfield = "0.12.0"
once_cell = "1.21.3"
pollster = "0.4.0"
puffin = "0.20.0"
puffin_egui = "0.30.0"
rfd = "0.15.4"
ringbuf = "0.4.8"
rubato = "0.16.2"
thiserror = "2.0.12"
wgpu = "27.0.0"
winit = "0.30.12"

